os: Visual Studio 2017

environment:
  matrix:

### MSVC Toolchains ###

  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
  # Stable 32-bit MSVC
    - channel: stable
      target: i686-pc-windows-msvc
  # Beta 64-bit MSVC
    - channel: beta
      target: x86_64-pc-windows-msvc
  # Beta 32-bit MSVC
    - channel: beta
      target: i686-pc-windows-msvc
  # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc
  # Nightly 32-bit MSVC
    - channel: nightly
      target: i686-pc-windows-msvc

  # 1.22.0 64-bit MSVC
    - channel: 1.22.0
      target: x86_64-pc-windows-msvc
  # 1.22.0 32-bit MSVC
    - channel: 1.22.0
      target: i686-pc-windows-msvc

### GNU Toolchains ###

  # Stable 64-bit GNU
    - channel: stable
      target: x86_64-pc-windows-gnu
  # Stable 32-bit GNU
    - channel: stable
      target: i686-pc-windows-gnu
  # Beta 64-bit GNU
    - channel: beta
      target: x86_64-pc-windows-gnu
  # Beta 32-bit GNU
    - channel: beta
      target: i686-pc-windows-gnu
  # Nightly 64-bit GNU
    - channel: nightly
      target: x86_64-pc-windows-gnu
  # Nightly 32-bit GNU
    - channel: nightly
      target: i686-pc-windows-gnu
  # 1.22.0 64-bit GNU
    - channel: 1.22.0
      target: x86_64-pc-windows-gnu
  # 1.22.0 32-bit GNU
    - channel: 1.22.0
      target: i686-pc-windows-gnu

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - if "%target%"=="x86_64-pc-windows-gnu"(set PATH=%PATH%;C:\msys64\mingw64\bin;C:\msys64\usr\bin)
  - if "%target%"=="i686-pc-windows-gnu"(set PATH=%PATH%;C:\msys64\mingw32\bin;C:\msys64\usr\bin)



build:
  - cargo build --verbose --features=fuzztarget
  - cargo build --verbose --features=rand
  - cargo build --verbose --no-default-features
  - cargo build --verbose --no-default-features --features="serde"
  - cargo build --verbose --no-default-features --features="rand"
  - cargo build --verbose --no-default-features --features="rand serde recovery endomorphism"
  - cargo build --verbose --no-default-features --features="fuzztarget recovery"
  - cargo build --verbose
  - cargo build --release

test_script:
  - cargo test --verbose --features=rand
  - cargo test --verbose --features="rand serde"
  - cargo test --verbose --features="rand serde recovery endomorphism"
  - cargo test --verbose
  - cargo test --release
  - if "%channel%"=="nightly" (cargo test --benches --features=unstable)
  # - if "%channel%"=="stable" (
  #   git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && emsdk install latest && emsdk activate latest --global && emsdk_env.bat &&
  #   cargo install --force cargo-web && cargo web build --target=asmjs-unknown-emscripten && cargo web test --target=asmjs-unknown-emscripten --nodejs)

cache:
  - 'C:\Users\appveyor\.cargo'
  - 'target'
